.bash:
  make:
    variables:
      - |
        # Make variables ..
        if [ ! -n $MODULE_DIR ]
        then
            echo "Error: MODULE_DIR is undefined"
            exit 1
        fi
        # we can't _transform_ variables inside Gitlab CI so we will use bash for it
        MODULE_DIR_RESOLVED=$(find $MODULE_DIR -mindepth 0 -maxdepth 0)
        MODULE_NAME=${MODULE_DIR#*-}
        IMAGE_NAME="${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}-${MODULE_NAME}:${CI_COMMIT_SHORT_SHA}"
        IMAGE_PREFIX="${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}-${MODULE_NAME}"
        CI_NAMESPACE="rev-${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${MODULE_NAME}"
  show:
    variables:
      - |
        # Show variables ..
        printf "
        MODULE_DIR:          ${MODULE_DIR}
        MODULE_DIR_RESOLVED: ${MODULE_DIR_RESOLVED}
        MODULE_NAME:         ${MODULE_NAME}
        CI_PIPELINE_URL:     ${CI_PIPELINE_URL}
        CI_ENVIRONMENT_URL:  ${CI_ENVIRONMENT_URL}
        CI_NAMESPACE:        ${CI_NAMESPACE}
        DOCKER_IMAGE:        ${IMAGE_NAME}
        "
      - |
        # See also /doc/docker_images_get_howto.txt
    release:
      - |
        cat /etc/*-release || true
